### ISSUE TITLE
Update the college name.

### ISSUE THREAD

**Issue by setco-website** [praveenscience/AP-GitHub-Praveen#1]
It's not SOME COLLEGE. Someone please fix it. Kindly do the needful for the greater good.

**Comment by tripathics** [comment]
Sir I would like to help

**Comment by sonu-paswan** [comment]
Yeah i would be interested in solving this issue

**Comment by praveenscience** [comment]
Yes, go ahead and fix it! 💪🏻

**Comment by karanakshat05** [comment]
Hey Praveen I would be glad to help you
